export const floorplans = [
    {"name": "thefoundation", "displayName": "THE FOUNDATION", "cost": 0, "types": ["Permanent", "Blueprint"], "rarity": 4, "entrances": 4},
    {"name": "entrancehall", "displayName": "ENTRANCE HALL", "cost": 0, "types": ["Permanent", "Blueprint"], "rarity": 0, "entrances": 4},
    {"name": "spareroom", "displayName": "SPARE ROOM", "cost": 0, "types": ["Blueprint"], "rarity": 1, "entrances": 2},
    {"name": "sparebedroom", "displayName": "SPARE BEDROOM", "cost": 0, "types": ["Bedroom", "Upgrade"], "rarity": 1, "entrances": 2},
    {"name": "sparegreenroom", "displayName": "SPARE GREENROOM", "cost": 0, "types": ["Green Room", "Upgrade"], "rarity": 1, "entrances": 2},
    {"name": "sparepatio", "displayName": "SPARE PATIO", "cost": 0, "types": ["Spread", "Green Room", "Upgrade"], "rarity": 1, "entrances": 2},
    {"name": "sparehall", "displayName": "SPARE HALL", "cost": 0, "types": ["Hallway", "Upgrade"], "rarity": 1, "entrances": 2},
    {"name": "sparesecretpassage", "displayName": "SPARE SECRET PASSAGE", "cost": 0, "types": ["Hallway", '"Dead End"', "Upgrade"], "rarity": 1, "entrances": 2},
    {"name": "rotunda", "displayName": "ROTUNDA", "cost": 3, "types": ["Blueprint"], "rarity": 4, "entrances": 4},
    {"name": "parlor", "displayName": "PARLOR", "cost": 0, "types": ["Puzzle", "Blueprint"], "rarity": 1, "entrances": 2},
    {"name": "funeralparlor", "displayName": "FUNERAL PARLOR", "cost": 0, "types": ["Puzzle", "Red Room", "Upgrade"], "rarity": 1, "entrances": 2},
    {"name": "billiardroom", "displayName": "BILLIARD ROOM", "cost": 0, "types": ["Puzzle", "Blueprint"], "rarity": 1, "entrances": 2},
    {"name": "breakroom", "displayName": "BREAK ROOM", "cost": 0, "types": ["Tomorrow", "Puzzle", "Blueprint", "Upgrade"], "rarity": 1, "entrances": 2},
    {"name": "poolhall", "displayName": "POOL HALL", "cost": 0, "types": ["Drafting", "Puzzle", "Hallway", "Upgrade"], "rarity": 1, "entrances": 2},
    {"name": "gallery", "displayName": "GALLERY", "cost": 0, "types": ["Puzzle", "Blueprint"], "rarity": 4, "entrances": 2},
    {"name": "room8", "displayName": "ROOM 8", "cost": 0, "types": ["Puzzle", "Blueprint"], "rarity": 4, "entrances": 2},
    {"name": "closet", "displayName": "CLOSET", "cost": 0, "types": ["Blueprint", "Dead End"], "rarity": 1, "entrances": 1},
    {"name": "emptycloset", "displayName": "EMPTY CLOSET", "cost": 0, "types": ["Red Room", "Dead End", "Upgrade"], "rarity": 1, "entrances": 1},
    {"name": "walkincloset", "displayName": "WALK-IN CLOSET", "cost": 1, "types": ["Blueprint", "Dead End"], "rarity": 2, "entrances": 1},
    {"name": "attic", "displayName": "ATTIC", "cost": 3, "types": ["Blueprint", "Dead End"], "rarity": 4, "entrances": 1},
    {"name": "storeroom", "displayName": "STOREROOM", "cost": 0, "types": ["Blueprint", "Dead End"], "rarity": 1, "entrances": 1},
    {"name": "nook", "displayName": "NOOK", "cost": 0, "types": ["Blueprint"], "rarity": 1, "entrances": 2},
    {"name": "readingnook", "displayName": "READING NOOK", "cost": 0, "types": ["Drafting", "Blueprint", "Upgrade"], "rarity": 1, "entrances": 2},
    {"name": "garage", "displayName": "GARAGE", "cost": 1, "types": ["Blueprint", '"Dead End"'], "rarity": 3, "entrances": 2},
    {"name": "musicroom", "displayName": "MUSIC ROOM", "cost": 2, "types": ["Blueprint"], "rarity": 3, "entrances": 2},
    {"name": "lockerroom", "displayName": "LOCKER ROOM", "cost": 1, "types": ["Spread", "Blueprint", "Addition"], "rarity": 4, "entrances": 2},
    {"name": "den", "displayName": "DEN", "cost": 0, "types": ["Blueprint"], "rarity": 1, "entrances": 3},
    {"name": "winecellar", "displayName": "WINE CELLAR", "cost": 0, "types": ["Blueprint", "Dead End"], "rarity": 3, "entrances": 1},
    {"name": "trophyroom", "displayName": "TROPHY ROOM", "cost": 5, "types": ["Blueprint"], "rarity": 4, "entrances": 2},
    {"name": "ballroom", "displayName": "BALLROOM", "cost": 2, "types": ["Entry", "Blueprint"], "rarity": 3, "entrances": 2},
    {"name": "pantry", "displayName": "PANTRY", "cost": 0, "types": ["Blueprint"], "rarity": 1, "entrances": 2},
    {"name": "rumpusroom", "displayName": "RUMPUS ROOM", "cost": 1, "types": ["Blueprint"], "rarity": 2, "entrances": 2},
    {"name": "vault", "displayName": "VAULT", "cost": 3, "types": ["Blueprint", "Dead End"], "rarity": 4, "entrances": 1},
    {"name": "office", "displayName": "OFFICE", "cost": 2, "types": ["Spread", "Blueprint"], "rarity": 2, "entrances": 2},
    {"name": "drawingroom", "displayName": "DRAWING ROOM", "cost": 1, "types": ["Drafting", "Blueprint"], "rarity": 1, "entrances": 3},
    {"name": "study", "displayName": "STUDY", "cost": 0, "types": ["Drafting", "Blueprint", "Dead End"], "rarity": 3, "entrances": 1},
    {"name": "library", "displayName": "LIBRARY", "cost": 0, "types": ["Drafting", "Blueprint"], "rarity": 3, "entrances": 2},
    {"name": "chamberofmirrors", "displayName": "CHAMBER OF MIRRORS", "cost": 0, "types": ["Drafting", "Blueprint", '"Dead End"'], "rarity": 4, "entrances": 4},
    {"name": "thepool", "displayName": "THE POOL", "cost": 1, "types": ["Drafting", "Blueprint"], "rarity": 2, "entrances": 3},
    {"name": "draftingstudio", "displayName": "DRAFTING STUDIO", "cost": 2, "types": ["Drafting", "Blueprint"], "rarity": 4, "entrances": 2},
    {"name": "utilitycloset", "displayName": "UTILITY CLOSET", "cost": 0, "types": ["Mechanical", "Blueprint", "Dead End"], "rarity": 2, "entrances": 1},
    {"name": "boilerroom", "displayName": "BOILER ROOM", "cost": 1, "types": ["Mechanical", "Blueprint"], "rarity": 3, "entrances": 3},
    {"name": "pumproom", "displayName": "PUMP ROOM", "cost": 0, "types": ["Mechanical", "Blueprint", "Addition"], "rarity": 3, "entrances": 2},
    {"name": "security", "displayName": "SECURITY", "cost": 1, "types": ["Mechanical", "Blueprint"], "rarity": 2, "entrances": 3},
    {"name": "workshop", "displayName": "WORKSHOP", "cost": 0, "types": ["Mechanical", "Blueprint"], "rarity": 3, "entrances": 2},
    {"name": "laboratory", "displayName": "LABORATORY", "cost": 1, "types": ["Mechanical", "Blueprint"], "rarity": 2, "entrances": 2},
    {"name": "sauna", "displayName": "SAUNA", "cost": 0, "types": ["Tomorrow", "Blueprint", "Dead End", "Addition"], "rarity": 3, "entrances": 1},
    {"name": "coatcheck", "displayName": "COAT CHECK", "cost": 0, "types": ["Tomorrow", "Blueprint", "Dead End"], "rarity": 2, "entrances": 1},
    {"name": "mailroom", "displayName": "MAIL ROOM", "cost": 0, "types": ["Tomorrow", "Blueprint", "Dead End"], "rarity": 3, "entrances": 1},
    {"name": "freezer", "displayName": "FREEZER", "cost": 0, "types": ["Tomorrow", "Blueprint", "Dead End"], "rarity": 4, "entrances": 1},
    {"name": "diningroom", "displayName": "DINING ROOM", "cost": 0, "types": ["Blueprint"], "rarity": 2, "entrances": 3},
    {"name": "observatory", "displayName": "OBSERVATORY", "cost": 1, "types": ["Blueprint"], "rarity": 2, "entrances": 2},
    {"name": "conferenceroom", "displayName": "CONFERENCE ROOM", "cost": 0, "types": ["Spread", "Blueprint"], "rarity": 3, "entrances": 3},
    {"name": "aquarium", "displayName": "AQUARIUM", "cost": 1, "types": ["Red Room", "Green Room", "Hallway", "Bedroom", "Shop", "Blackprint", "Blueprint"], "rarity": 3, "entrances": 3},
    {"name": "electriceelaquarium", "displayName": "ELECTRIC EEL AQUARIUM", "cost": 1, "types": ["Mechanical", "Red Room", "Green Room", "Hallway", "Bedroom", "Shop", "Blackprint", "Blueprint", "Upgrade"], "rarity": 3, "entrances": 3},
    {"name": "antechamber", "displayName": "ANTECHAMBER", "cost": 0, "types": ["Blueprint", "Objective"], "rarity": 0, "entrances": 4},
    {"name": "room46", "displayName": "ROOM 46", "cost": 0, "types": ["Blueprint", "Objective"], "rarity": 5, "entrances": 1},
    {"name": "bedroom", "displayName": "BEDROOM", "cost": 0, "types": ["Entry", "Bedroom"], "rarity": 1, "entrances": 2},
    {"name": "boudoir", "displayName": "BOUDOIR", "cost": 0, "types": ["Bedroom"], "rarity": 2, "entrances": 2},
    {"name": "guestbedroom", "displayName": "GUEST BEDROOM", "cost": 0, "types": ["Bedroom", "Dead End"], "rarity": 1, "entrances": 1},
    {"name": "nursery", "displayName": "NURSERY", "cost": 1, "types": ["Drafting", "Bedroom", "Dead End"], "rarity": 1, "entrances": 1},
    {"name": "nursesstation", "displayName": "NURSE'S STATION", "cost": 1, "types": ["Entry", "Bedroom", "Dead End", "Upgrade"], "rarity": 1, "entrances": 1},
    {"name": "indoornursery", "displayName": "INDOOR NURSERY", "cost": 1, "types": ["Drafting", "Green Room", "Dead End", "Upgrade"], "rarity": 1, "entrances": 1},
    {"name": "servantsquarters", "displayName": "SERVANT'S QUARTERS", "cost": 1, "types": ["Bedroom", "Dead End"], "rarity": 3, "entrances": 1},
    {"name": "bunkroom", "displayName": "BUNK ROOM", "cost": 0, "types": ["Bedroom", "Bedroom", "Dead End", "Dead End"], "rarity": 3, "entrances": 1},
    {"name": "herladyshipschamber", "displayName": "HER LADYSHIP'S CHAMBER", "cost": 0, "types": ["Bedroom", "Dead End"], "rarity": 4, "entrances": 1},
    {"name": "masterbedroom", "displayName": "MASTER BEDROOM", "cost": 2, "types": ["Bedroom", "Dead End"], "rarity": 4, "entrances": 1},
    {"name": "hallway", "displayName": "HALLWAY", "cost": 0, "types": ["Hallway"], "rarity": 1, "entrances": 3},
    {"name": "hallway2", "displayName": "HALLWAY", "cost": 0, "types": ["Tomorrow", "Hallway", "Upgrade"], "rarity": 1, "entrances": 3},
    {"name": "westwinghall", "displayName": "WEST WING HALL", "cost": 0, "types": ["Hallway"], "rarity": 2, "entrances": 3},
    {"name": "eastwinghall", "displayName": "EAST WING HALL", "cost": 0, "types": ["Hallway"], "rarity": 3, "entrances": 3},
    {"name": "corridor", "displayName": "CORRIDOR", "cost": 0, "types": ["Hallway"], "rarity": 1, "entrances": 2},
    {"name": "passageway", "displayName": "PASSAGEWAY", "cost": 2, "types": ["Hallway"], "rarity": 1, "entrances": 4},
    {"name": "secretpassage", "displayName": "SECRET PASSAGE", "cost": 1, "types": ["Hallway", '"Dead End"'], "rarity": 2, "entrances": 2},
    {"name": "foyer", "displayName": "FOYER", "cost": 2, "types": ["Hallway"], "rarity": 3, "entrances": 2},
    {"name": "greathall", "displayName": "GREAT HALL", "cost": 0, "types": ["Hallway"], "rarity": 3, "entrances": 4},
    {"name": "terrace", "displayName": "TERRACE", "cost": 0, "types": ["Green Room", "Dead End"], "rarity": 2, "entrances": 1},
    {"name": "patio", "displayName": "PATIO", "cost": 1, "types": ["Spread", "Green Room"], "rarity": 2, "entrances": 2},
    {"name": "courtyard", "displayName": "COURTYARD", "cost": 1, "types": ["Green Room"], "rarity": 2, "entrances": 3},
    {"name": "corriyard", "displayName": "CORRIYARD", "cost": 1, "types": ["Green Room", "Hallway", "Upgrade"], "rarity": 2, "entrances": 3},
    {"name": "cloister", "displayName": "CLOISTER", "cost": 3, "types": ["Green Room"], "rarity": 3, "entrances": 4},
    {"name": "cloisteroforinda", "displayName": "CLOISTER OF ORINDA", "cost": 3, "types": ["Blackprint", "Upgrade"], "rarity": 3, "entrances": 4},
    {"name": "cloisterofdraxus", "displayName": "CLOISTER OF DRAXUS", "cost": 0, "types": ["Red Room", "Upgrade"], "rarity": 3, "entrances": 4},
    {"name": "veranda", "displayName": "VERANDA", "cost": 2, "types": ["Green Room"], "rarity": 3, "entrances": 2},
    {"name": "greenhouse", "displayName": "GREENHOUSE", "cost": 1, "types": ["Drafting", "Green Room", "Dead End"], "rarity": 2, "entrances": 1},
    {"name": "greenhousesecret", "displayName": "GREENHOUSE", "cost": 1, "types": ["Green Room", ""], "rarity": 2, "entrances": 2},
    {"name": "morningroom", "displayName": "MORNING ROOM", "cost": 0, "types": ["Tomorrow", "Green Room", "Addition"], "rarity": 4, "entrances": 2},
    {"name": "secretgarden", "displayName": "SECRET GARDEN", "cost": 0, "types": ["Spread", "Green Room"], "rarity": 4, "entrances": 3},
    {"name": "commissary", "displayName": "COMMISSARY", "cost": 1, "types": ["Shop"], "rarity": 2, "entrances": 2},
    {"name": "kitchen", "displayName": "KITCHEN", "cost": 1, "types": ["Shop"], "rarity": 1, "entrances": 2},
    {"name": "locksmith", "displayName": "LOCKSMITH", "cost": 1, "types": ["Shop", "Dead End"], "rarity": 3, "entrances": 1},
    {"name": "showroom", "displayName": "SHOWROOM", "cost": 2, "types": ["Shop"], "rarity": 4, "entrances": 2},
    {"name": "laundryroom", "displayName": "LAUNDRY ROOM", "cost": 1, "types": ["Shop", "Dead End"], "rarity": 4, "entrances": 1},
    {"name": "bookshop", "displayName": "BOOKSHOP", "cost": 1, "types": ["Shop"], "rarity": 4, "entrances": 2},
    {"name": "thearmory", "displayName": "THE ARMORY", "cost": 0, "types": ["Shop", "Blackprint"], "rarity": 2, "entrances": 2},
    {"name": "mounthollygiftshop", "displayName": "MOUNT HOLLY GIFT SHOP", "cost": 0, "types": ["Shop", "Addition"], "rarity": 4, "entrances": 3},
    {"name": "lavatory", "displayName": "LAVATORY", "cost": 0, "types": ["Red Room", "Dead End"], "rarity": 2, "entrances": 1},
    {"name": "chapel", "displayName": "CHAPEL", "cost": 0, "types": ["Entry", "Red Room"], "rarity": 1, "entrances": 3},
    {"name": "maidschamber", "displayName": "MAID'S CHAMBER", "cost": 0, "types": ["Red Room", "Bedroom"], "rarity": 3, "entrances": 2},
    {"name": "archives", "displayName": "ARCHIVES", "cost": 0, "types": ["Red Room"], "rarity": 3, "entrances": 4},
    {"name": "gymnasium", "displayName": "GYMNASIUM", "cost": 0, "types": ["Entry", "Red Room"], "rarity": 2, "entrances": 3},
    {"name": "darkroom", "displayName": "DARKROOM", "cost": 0, "types": ["Red Room"], "rarity": 2, "entrances": 3},
    {"name": "weightroom", "displayName": "WEIGHT ROOM", "cost": 0, "types": ["Red Room"], "rarity": 4, "entrances": 4},
    {"name": "furnace", "displayName": "FURNACE", "cost": 0, "types": ["Red Room", "Dead End"], "rarity": 4, "entrances": 1},
    {"name": "dovecote", "displayName": "DOVECOTE", "cost": 0, "types": ["Blueprint", "Addition"], "rarity": 3, "entrances": 2},
    {"name": "thekennel", "displayName": "THE KENNEL", "cost": 0, "types": ["Blueprint", "Addition"], "rarity": 2, "entrances": 2},
    {"name": "clocktower", "displayName": "CLOCKTOWER", "cost": 1, "types": ["Tomorrow", "Blueprint", "Dead End", "Addition"], "rarity": 3, "entrances": 1},
    {"name": "classroom", "displayName": "CLASSROOM", "cost": 1, "types": ["Drafting", "Blueprint", "Addition"], "rarity": 3, "entrances": 2},
    {"name": "solarium", "displayName": "SOLARIUM", "cost": 1, "types": ["Green Room", "Dead End", "Addition"], "rarity": 2, "entrances": 1},
    {"name": "dormitory", "displayName": "DORMITORY", "cost": 0, "types": ["Entry", "Bedroom", "Dead End", "Addition"], "rarity": 2, "entrances": 1},
    {"name": "vestibule", "displayName": "VESTIBULE", "cost": 2, "types": ["Entry", "Hallway", "Addition"], "rarity": 3, "entrances": 4},
    {"name": "casino", "displayName": "CASINO", "cost": 2, "types": ["Shop", "Addition"], "rarity": 3, "entrances": 2},
    {"name": "planetarium", "displayName": "PLANETARIUM", "cost": 0, "types": ["Tomorrow", "Blueprint", "Dead End", "Addition"], "rarity": 2, "entrances": 1},
    {"name": "mechanarium", "displayName": "MECHANARIUM", "cost": 0, "types": ["Mechanical", "Blueprint", "Addition"], "rarity": 3, "entrances": 4},
    {"name": "treasuretrove", "displayName": "TREASURE TROVE", "cost": 1, "types": ["Blackprint", "Addition"], "rarity": 3, "entrances": 2},
    {"name": "throneroom", "displayName": "THRONEROOM", "cost": 5, "types": ["Blackprint", "Addition"], "rarity": 4, "entrances": 3},
    {"name": "throneoftheblueprince", "displayName": "THRONE OF THE BLUE PRINCE", "cost": 5, "types": ["Drafting", "Blueprint", "Addition"], "rarity": 4, "entrances": 3},
    {"name": "tunnel", "displayName": "TUNNEL", "cost": 0, "types": ["Drafting", "Hallway", "Addition"], "rarity": 2, "entrances": 2},
    {"name": "conservatory", "displayName": "CONSERVATORY", "cost": 1, "types": ["Drafting", "Green Room", "Addition"], "rarity": 3, "entrances": 2},
    {"name": "lostfound", "displayName": "LOST & FOUND", "cost": 0, "types": ["Entry", "Red Room", "Addition"], "rarity": 3, "entrances": 2},
    {"name": "closedexhibit", "displayName": "CLOSED EXHIBIT", "cost": 0, "types": ["Red Room", "Addition"], "rarity": 4, "entrances": 3},
    {"name": "toolshed", "displayName": "TOOLSHED", "cost": 0, "types": ["Blueprint", "Dead End", "Outer Room"], "rarity": 3, "entrances": 1},
    {"name": "shelter", "displayName": "SHELTER", "cost": 0, "types": ["Blueprint", "Dead End", "Outer Room"], "rarity": 3, "entrances": 1},
    {"name": "schoolhouse", "displayName": "SCHOOLHOUSE", "cost": 0, "types": ["Drafting", "Blueprint", "Dead End", "Outer Room"], "rarity": 3, "entrances": 1},
    {"name": "shrine", "displayName": "SHRINE", "cost": 0, "types": ["Blueprint", "Dead End", "Outer Room"], "rarity": 3, "entrances": 1},
    {"name": "rootcellar", "displayName": "ROOT CELLAR", "cost": 0, "types": ["Green Room", "Dead End", "Outer Room"], "rarity": 3, "entrances": 1},
    {"name": "hovel", "displayName": "HOVEL", "cost": 0, "types": ["Bedroom", "Dead End", "Outer Room"], "rarity": 3, "entrances": 1},
    {"name": "tradingpost", "displayName": "TRADING POST", "cost": 0, "types": ["Shop", "Dead End", "Outer Room"], "rarity": 3, "entrances": 1},
    {"name": "tomb", "displayName": "TOMB", "cost": 0, "types": ["Blackprint", "Dead End", "Outer Room"], "rarity": 3, "entrances": 2}
];